### ISSUE TITLE
No data for individual district

### ISSUE THREAD

**Issue by emtiazzahid** [TeamTigers/coronainfobd#18]
**Describe the bug**
Not getting district-wise data in Map Visualization section

**To Reproduce**
1. Go to ['coronainfobd'](https://teamtigers.github.io/coronainfobd/)
2. Hover/Click on 'Map Visualization > district name'
3. Showing all values zero. 

**Expected behavior**
Might be a lack of data. It can be hidden or show the last updated date

**Screenshots**
![image](https://user-images.githubusercontent.com/10188029/91031997-29ef1680-e623-11ea-9890-4fd388c92987.png)

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]
 - Version [84.0.4147.135 (Official Build) (64-bit)]

**Comment by zubayerhimel** [comment]
@emtiazzahid, Thank you for opening the issue. We're having this problem because we've used an external [API](https://github.com/ahmedsadman/covid19-bd) to visualize the map. But it seems there is a problem accessing the API. That's why we're not getting any response. We've also faced related problem before. If the respective owner ( @ahmedsadman ) of the API fix his API link we'll then get data. Please wait some time. 
![Screenshot from 2020-08-24 19-44-40](https://user-images.githubusercontent.com/29749035/91051706-4e0e2000-e642-11ea-9de6-ab5f354d718d.png)

**Comment by ahmedsadman** [comment]
Hi, I am very much aware of this issue and this is _intentional_. You're instructed to implement caching in your application: https://github.com/ahmedsadman/covid19-bd/issues/8#event-3686548808

**Comment by shunjid** [comment]
**Improvements required**
- Show cached data previously fetched from [API](https://github.com/ahmedsadman/covid19-bd) only if a request fails.

**Required improvement at**
- File: **assets/js/map-controller.js** line [7-12](https://github.com/TeamTigers/coronainfobd/blob/master/assets/js/map-controller.js)
```javascript
$.get(districtUrl, function () {})
  .done(function (response) {
  districtData = response.data;
});
```

**Comment by ahmedsadman** [comment]
@shunjid Show cached data only if a request fails., don't depend on DateTime. As things are now, the server on/off is manual. So it is not possible for me to follow strict DateTime. The data might be delayed for more than 1 day. 
I know it's not a solution at all, but I don't have any alternate option now. I can't afford server costs. I have added a donation option which might help me to keep the project alive. Sorry for the problem

**Comment by shunjid** [comment]
@ahmedsadman 

We can understand the situation. 

All, I can suggest you at this point is to try [GitHub's Student Pack for Heroku](https://www.heroku.com/github-students) till you get funds to continue this great project. Thanks for your contribution to the community. :+1: :tada:

**Comment by ahmedsadman** [comment]
The project was running on education pack credits. Anyway, let's hope for the best
